[target.thumbv6m-none-eabi]
runner = "probe-run --chip ATSAMD21E17A --speed 400"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
